name: darksky_weather
description: A dart library for interfacing with the Dark Sky Weather API.
version: 1.4.1+1
homepage: https://github.com/rinukkusu/darksky-weather-dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  json_annotation: ^3.0.0
  http: '^0.12.0'

dev_dependencies:
  test: ^1.3.0
  json_serializable: ^3.0.0
  build_runner: ^1.1.2

